FIX: Check if notify-send is available
This check makes sure that notify-send is available before continuing.

diff --git a/booky b/booky
--- a/booky
+++ b/booky
@@ -93,6 +93,12 @@ check() {
         echo "dmenu is not installed, aborting!"
         exit 1
     fi
+
+    ret_notify=`which notify-send`
+    if test $? -eq 1; then
+        echo "notify-send not installed, aborting!"
+        exit 1
+    fi
 }
 
 main() {
